services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack
    restart: unless-stopped
    depends_on:
      bookstack-db:
        condition: service_healthy
    ports:
      - "6875:80"
    environment:
      - TZ=Etc/UTC
      - APP_URL=wiki.urbanairlab.hn
      - APP_KEY=${BOOKSTACK_APP_KEY}
      - DB_HOST=bookstack-db
      - DB_PORT=3306
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - bookstack_config:/config
    networks:
      - frontend
      - bookstack
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=community_frontend"

      - "traefik.http.routers.bookstack-secure.rule=Host(`wiki.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.bookstack-secure.entrypoints=websecure"
      - "traefik.http.routers.bookstack-secure.tls=true"
      - "traefik.http.routers.bookstack-secure.tls.certresolver=myresolver"

  bookstack-db:
    image: mysql:8.0
    container_name: bookstack-db
    restart: unless-stopped
    environment:
      - TZ=Etc/UTC
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - bookstack_data:/var/lib/mysql
    networks:
      - bookstack
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

networks:
  bookstack:
  frontend:

volumes:
  bookstack_config:
  bookstack_data:

